local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>tf", function() 
    builtin.find_files({ hidden = true})
end)
vim.keymap.set("n", "<leader>tv", builtin.git_files)
vim.keymap.set("n", "<leader>tg", builtin.live_grep)
vim.keymap.set("n", "<leader>te", builtin.diagnostics)
